// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZV9YCw2CIQTHesjcVKCFbqvUTRgq8Oks',
    appId: '1:558035200930:web:683ffe04007bdb9a4c60fb',
    messagingSenderId: '558035200930',
    projectId: 'savestep',
    authDomain: 'savestep.firebaseapp.com',
    storageBucket: 'savestep.firebasestorage.app',
    measurementId: 'G-D74CCGSGVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWvnchbs3eVOmrkxopCQdWmU2o_lTk9ts',
    appId: '1:558035200930:android:7c4a816fc804eb954c60fb',
    messagingSenderId: '558035200930',
    projectId: 'savestep',
    storageBucket: 'savestep.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZV9YCw2CIQTHesjcVKCFbqvUTRgq8Oks',
    appId: '1:558035200930:web:ba9e1e8fc360848a4c60fb',
    messagingSenderId: '558035200930',
    projectId: 'savestep',
    authDomain: 'savestep.firebaseapp.com',
    storageBucket: 'savestep.firebasestorage.app',
    measurementId: 'G-5C3DVC0WX0',
  );
}
